name: RedMovie Auto Updater

on:
  schedule:
    - cron: '*/30 * * * *' # هر 30 دقیقه یکبار خودکار اجرا می‌شود[cite: 8]
  workflow_dispatch: # امکان اجرای دستی ربات[cite: 8]

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest[cite: 8]

    steps:
    - name: Checkout code[cite: 8]
      uses: actions/checkout@v3[cite: 8]

    - name: Setup Node.js[cite: 8]
      uses: actions/setup-node@v3[cite: 8]
      with:
        node-version: '18'[cite: 8]

    - name: Install dependencies[cite: 8]
      run: npm install[cite: 8]

    - name: Run Scraper Bot[cite: 8]
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }} # خواندن ایمن لینک دیتابیس از سکرت گیت‌هاب[cite: 8]
      run: node scraper-bot.js[cite: 8]
